export const CONSOLIDATION_BLOCKING_SCALAR_FIELDS = [
  'weight',
  'height',
  'bodyFatPercentage',
  'vo2Max',
  'anaerobicThreshold',
  'maxHeartRate',
  'restingHeartRate',
  'systolicPressure',
  'diastolicPressure',
] as const;

export const CONSOLIDATION_BLOCKING_OWNERSHIP_RELATIONS = [
  'agendaBookings',
  'anthropometryAssessments',
  'exerciseProgress',
  'intakeForm',
  'profileReviewSettings',
  'assessmentPlanItems',
  'assessments',
  'contracts',
  'studentContracts',
  'fixedSlots',
  'integrations',
  'macronutrients',
  'nutritionPlans',
  'progressMetrics',
  'executions',
  'trainingPlans',
  'workoutExecutions',
  'studentHealthIntake',
  'studentAssessmentRecords',
  'studentFinancialProfile',
  'studentExternalAccounts',
  'studentExternalActivities',
  'parqSubmissions',
  'parqDraft',
  'parqProfessionalReviews',
  'parqLegacyRecords',
  'prontuarioRecords',
  'prontuarioDiscomfortSnapshots',
  'guardianAuthorizations',
] as const;

export const CONSOLIDATION_PRESERVED_SOURCE_HISTORY_RELATIONS = [
  'studentProfile',
  'profileReviews',
  'profileAuditLogs',
  'onboarding',
  'lifecycleEvents',
  'preRegistrationInvites',
] as const;
