CREATE TABLE "PostWorkoutFeedbackRevision" (
"id" TEXT NOT NULL,"workoutDayId" TEXT NOT NULL,"executionId" TEXT NOT NULL,"alunoId" TEXT NOT NULL,"contractId" TEXT NOT NULL,"scopeKey" TEXT NOT NULL DEFAULT 'session',"capacity" TEXT,"revisionNumber" INTEGER NOT NULL,"previousRevisionId" TEXT,"perceptionAuthorActor" TEXT NOT NULL,"perceptionAuthorUserId" TEXT,"revisedByActor" TEXT NOT NULL,"revisedByUserId" TEXT,"correctionReason" TEXT,"values" JSONB NOT NULL,"signals" JSONB NOT NULL,"ruleSetVersion" TEXT NOT NULL,"originReleaseId" TEXT NOT NULL,"originWorkoutTemplateId" TEXT NOT NULL,"originTrainingPlanId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PostWorkoutFeedbackRevision_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PostWorkoutFeedbackOperation" ("id" TEXT NOT NULL,"workoutDayId" TEXT NOT NULL,"scopeKey" TEXT NOT NULL,"operationKey" TEXT NOT NULL,"payloadFingerprint" TEXT NOT NULL,"action" TEXT NOT NULL,"baseRevisionId" TEXT,"resultingRevisionId" TEXT NOT NULL,"lifecycleEventId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PostWorkoutFeedbackOperation_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PostWorkoutFeedbackRevision_workoutDayId_scopeKey_revisionNumber_key" ON "PostWorkoutFeedbackRevision"("workoutDayId","scopeKey","revisionNumber");
CREATE INDEX "PostWorkoutFeedbackRevision_workoutDayId_scopeKey_createdAt_idx" ON "PostWorkoutFeedbackRevision"("workoutDayId","scopeKey","createdAt");
CREATE INDEX "PostWorkoutFeedbackRevision_executionId_idx" ON "PostWorkoutFeedbackRevision"("executionId");
CREATE INDEX "PostWorkoutFeedbackRevision_alunoId_contractId_createdAt_idx" ON "PostWorkoutFeedbackRevision"("alunoId","contractId","createdAt");
CREATE UNIQUE INDEX "PostWorkoutFeedbackOperation_workoutDayId_scopeKey_operationKey_key" ON "PostWorkoutFeedbackOperation"("workoutDayId","scopeKey","operationKey");
CREATE INDEX "PostWorkoutFeedbackOperation_resultingRevisionId_idx" ON "PostWorkoutFeedbackOperation"("resultingRevisionId");
CREATE INDEX "PostWorkoutFeedbackOperation_createdAt_idx" ON "PostWorkoutFeedbackOperation"("createdAt");
ALTER TABLE "PostWorkoutFeedbackRevision" ADD CONSTRAINT "PostWorkoutFeedbackRevision_workoutDayId_fkey" FOREIGN KEY ("workoutDayId") REFERENCES "WorkoutDay"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PostWorkoutFeedbackRevision" ADD CONSTRAINT "PostWorkoutFeedbackRevision_executionId_fkey" FOREIGN KEY ("executionId") REFERENCES "WorkoutSessionExecution"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PostWorkoutFeedbackRevision" ADD CONSTRAINT "PostWorkoutFeedbackRevision_previousRevisionId_fkey" FOREIGN KEY ("previousRevisionId") REFERENCES "PostWorkoutFeedbackRevision"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PostWorkoutFeedbackOperation" ADD CONSTRAINT "PostWorkoutFeedbackOperation_resultingRevisionId_fkey" FOREIGN KEY ("resultingRevisionId") REFERENCES "PostWorkoutFeedbackRevision"("id") ON DELETE CASCADE ON UPDATE CASCADE;
